import "~/styles/globals.css";
import "~/styles/stars.scss";

import { GeistSans } from "geist/font/sans";
import Link from "next/link";

export const metadata = {
  title: "StarlitMC",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

//currently pushes to the left
function TopNav() {
  return (
    <nav className="flex justify-between text-center items-center grid-cols-5 p-4 font-semibold">
      <Link href="/">News</Link>
      <Link href="/about">Store</Link>
      <Link href="/contact" className="text-5xl">StarlitMC</Link>
      <Link href="/blog">Vote</Link>
      <Link href="/projects">Sign In</Link>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TopNav />
        {children}
        <div id="stars"></div>
        <div id="stars2"></div>
        <div id="stars3"></div>
      </body>
    </html>
  );
}
